name = "highcharts-cdn"
main = "src/index.js"
compatibility_date = "2023-01-02"

account_id = "00187096e512bdfc9843343a98b67992" # ← Replace with your Account ID.
workers_dev = true


[[r2_buckets]]
binding = 'R2_BUCKET' # <~ valid JavaScript variable name
bucket_name = 'highcharts-code'

[vars]
CDN_DOMAIN = "code.highcharts.dev"
LegacyDomain = "cdn.hcharts.cn"
HIGHCHARTS_VERSION = "10.3.2"
